const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const {
  bumpSemver,
  parseCliArgs,
  runVersionBump,
} = require('../core.js');

function writeFile(filePath, content) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, 'utf8');
}

function writeJson(filePath, value) {
  writeFile(filePath, `${JSON.stringify(value, null, 2)}\n`);
}

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, 'utf8'));
}

function createFixtureRepo() {
  const repoRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'oneflowbase-bump-version-'));

  writeJson(path.join(repoRoot, 'web', 'app', 'package.json'), {
    name: '@1flowbase/web',
    version: '0.1.1',
  });
  writeJson(path.join(repoRoot, 'web', 'packages', 'api-client', 'package.json'), {
    name: '@1flowbase/api-client',
    version: '0.1.0',
  });

  writeFile(
    path.join(repoRoot, 'api', 'Cargo.toml'),
    `[workspace]
members = [
  "apps/api-server",
  "apps/plugin-runner",
  "crates/domain"
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
version = "0.1.0"
`
  );
  writeFile(
    path.join(repoRoot, 'api', 'apps', 'api-server', 'Cargo.toml'),
    `[package]
name = "api-server"
version = "0.1.0"
edition.workspace = true
`
  );
  writeFile(
    path.join(repoRoot, 'api', 'apps', 'plugin-runner', 'Cargo.toml'),
    `[package]
name = "plugin-runner"
version = "0.1.0"
edition.workspace = true
`
  );
  writeFile(
    path.join(repoRoot, 'api', 'crates', 'domain', 'Cargo.toml'),
    `[package]
name = "domain"
version.workspace = true
edition.workspace = true
`
  );
  writeFile(
    path.join(repoRoot, 'api', 'Cargo.lock'),
    `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "api-server"
version = "0.1.0"

[[package]]
name = "domain"
version = "0.1.0"

[[package]]
name = "plugin-runner"
version = "0.1.0"

[[package]]
name = "serde"
version = "1.0.0"
`
  );

  writeFile(
    path.join(repoRoot, 'docker', '.env.example'),
    `FLOWBASE_WEB_VERSION=latest
FLOWBASE_API_SERVER_VERSION=latest
FLOWBASE_PLUGIN_RUNNER_VERSION=latest
POSTGRES_DB=1flowbase
`
  );
  writeFile(
    path.join(repoRoot, 'docker', '.env'),
    `FLOWBASE_WEB_VERSION=0.0.1
FLOWBASE_API_SERVER_VERSION=0.0.1
FLOWBASE_PLUGIN_RUNNER_VERSION=0.0.1
POSTGRES_DB=1flowbase
`
  );
  writeFile(
    path.join(repoRoot, 'api', 'plugins', 'templates', 'fixture', 'manifest.yaml'),
    `name: fixture
version: 0.1.0
`
  );

  return repoRoot;
}

test('parseCliArgs defaults to applying a patch bump', () => {
  assert.deepEqual(parseCliArgs([]), {
    dryRun: false,
    help: false,
    release: 'patch',
    targetVersion: null,
  });
});

test('bumpSemver increments the requested segment', () => {
  assert.equal(bumpSemver('0.1.9', 'patch'), '0.1.10');
  assert.equal(bumpSemver('0.1.9', 'minor'), '0.2.0');
  assert.equal(bumpSemver('0.1.9', 'major'), '1.0.0');
});

test('runVersionBump previews changes during dry-run without writing files', () => {
  const repoRoot = createFixtureRepo();
  const originalPackage = fs.readFileSync(path.join(repoRoot, 'web', 'app', 'package.json'), 'utf8');
  const output = [];

  const status = runVersionBump({
    repoRoot,
    options: parseCliArgs(['--dry-run']),
    writeStdout: (text) => output.push(text),
  });

  assert.equal(status, 0);
  assert.equal(fs.readFileSync(path.join(repoRoot, 'web', 'app', 'package.json'), 'utf8'), originalPackage);
  assert.match(output.join(''), /dry-run/u);
  assert.match(output.join(''), /web\/app\/package\.json/u);
});

test('runVersionBump updates frontend, backend, and lockfile versions', () => {
  const repoRoot = createFixtureRepo();
  const originalDockerExample = fs.readFileSync(path.join(repoRoot, 'docker', '.env.example'), 'utf8');
  const originalDockerEnv = fs.readFileSync(path.join(repoRoot, 'docker', '.env'), 'utf8');

  const status = runVersionBump({
    repoRoot,
    options: parseCliArgs([]),
    writeStdout: () => {},
  });

  assert.equal(status, 0);
  assert.equal(readJson(path.join(repoRoot, 'web', 'app', 'package.json')).version, '0.1.2');
  assert.equal(readJson(path.join(repoRoot, 'web', 'packages', 'api-client', 'package.json')).version, '0.1.1');

  assert.match(fs.readFileSync(path.join(repoRoot, 'api', 'Cargo.toml'), 'utf8'), /version = "0\.1\.1"/u);
  assert.match(
    fs.readFileSync(path.join(repoRoot, 'api', 'apps', 'api-server', 'Cargo.toml'), 'utf8'),
    /version = "0\.1\.1"/u
  );
  assert.match(
    fs.readFileSync(path.join(repoRoot, 'api', 'apps', 'plugin-runner', 'Cargo.toml'), 'utf8'),
    /version = "0\.1\.1"/u
  );

  const lockfile = fs.readFileSync(path.join(repoRoot, 'api', 'Cargo.lock'), 'utf8');
  assert.match(lockfile, /name = "domain"\nversion = "0\.1\.1"/u);
  assert.match(lockfile, /name = "serde"\nversion = "1\.0\.0"/u);

  assert.equal(fs.readFileSync(path.join(repoRoot, 'docker', '.env.example'), 'utf8'), originalDockerExample);
  assert.equal(fs.readFileSync(path.join(repoRoot, 'docker', '.env'), 'utf8'), originalDockerEnv);

  assert.equal(
    fs.readFileSync(path.join(repoRoot, 'api', 'plugins', 'templates', 'fixture', 'manifest.yaml'), 'utf8'),
    `name: fixture
version: 0.1.0
`
  );
});

test('runVersionBump can pin every owned component to an explicit version', () => {
  const repoRoot = createFixtureRepo();

  const status = runVersionBump({
    repoRoot,
    options: parseCliArgs(['--to', '0.3.0']),
    writeStdout: () => {},
  });

  assert.equal(status, 0);
  assert.equal(readJson(path.join(repoRoot, 'web', 'app', 'package.json')).version, '0.3.0');
  assert.match(fs.readFileSync(path.join(repoRoot, 'api', 'Cargo.toml'), 'utf8'), /version = "0\.3\.0"/u);
  assert.match(
    fs.readFileSync(path.join(repoRoot, 'docker', '.env.example'), 'utf8'),
    /FLOWBASE_API_SERVER_VERSION=latest/u
  );
  assert.match(fs.readFileSync(path.join(repoRoot, 'docker', '.env'), 'utf8'), /FLOWBASE_API_SERVER_VERSION=0\.0\.1/u);
});
