const fs = require('node:fs');
const path = require('node:path');

const { getPluginName, sanitizeCode } = require('./fs.js');

function createManifestTemplate({ pluginCode, pluginName }) {
  return `manifest_version: 1
plugin_id: ${pluginCode}
version: 0.1.0
vendor: 1flowbase
display_name: ${pluginName}
description: OpenAI-compatible provider runtime extension
source_kind: official_registry
trust_level: verified_official
consumption_kind: runtime_extension
execution_mode: process_per_call
slot_codes:
  - model_provider
binding_targets:
  - workspace
selection_mode: assignment_then_select
minimum_host_version: 0.1.0
contract_version: 1flowbase.provider/v1
schema_version: 1flowbase.plugin.manifest/v1
permissions:
  network: outbound_only
  secrets: provider_instance_only
  storage: none
  mcp: none
  subprocess: deny
runtime:
  protocol: stdio_json
  entry: bin/${pluginCode}-provider
  limits:
    timeout_ms: 30000
    memory_bytes: 268435456
node_contributions: []
`;
}

function createProviderYamlTemplate({ pluginCode, pluginName }) {
  return `provider_code: ${pluginCode}
display_name: ${pluginName}
help_url: https://example.com/${pluginCode}
default_base_url: https://api.example.com
model_discovery: hybrid
config_schema:
  - key: base_url
    type: string
    required: true
  - key: api_key
    type: secret
    required: true
`;
}

function createCargoTomlTemplate({ pluginCode }) {
  return `[package]
name = "${pluginCode}-provider"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
`;
}

function createRustMainTemplate({ pluginCode }) {
  return `use std::io::{self, Read};

fn main() {
    let mut stdin = String::new();
    if let Err(error) = io::stdin().read_to_string(&mut stdin) {
        eprintln!("failed to read stdin: {}", error);
        std::process::exit(1);
    }

    let payload: serde_json::Value =
        serde_json::from_str(&stdin).unwrap_or(serde_json::Value::Null);
    let model = payload
        .get("input")
        .and_then(|value| value.get("model"))
        .and_then(|value| value.as_str())
        .unwrap_or("generated-rust-scaffold");

    println!(
        "{}",
        serde_json::json!({
            "ok": true,
            "result": {
                "provider_code": "${pluginCode}",
                "message": "generated rust scaffold",
                "echo_model": model,
            }
        })
    );
}
`;
}

function createExampleModelYaml({ pluginCode }) {
  return `model: ${pluginCode}_chat
label: Example Chat Model
family: llm
capabilities:
  - stream
  - tool_call
  - usage
`;
}

function createI18nTemplate({ pluginName, locale }) {
  const isChinese = locale === 'zh_Hans';
  return JSON.stringify(
    {
      plugin: {
        label: pluginName,
        description: isChinese
          ? `${pluginName} 运行时扩展脚手架`
          : `${pluginName} runtime extension scaffold`,
      },
      provider: {
        label: pluginName,
      },
      demo: {
        title: isChinese ? `${pluginName} 调试页` : `${pluginName} Demo`,
      },
    },
    null,
    2
  ) + '\n';
}

function createReadmeTemplate({ pluginCode, pluginName }) {
  return `# ${pluginName}

This scaffold was generated by \`node scripts/node/plugin/cli.js init\`.

## Provider Code

- \`${pluginCode}\`

## Next Steps

1. Replace \`src/main.rs\` with the real provider runtime.
2. Update \`manifest.yaml\`, \`provider/${pluginCode}.yaml\`, and \`models/llm/*.yaml\`.
3. If this is an official provider, place it under \`runtime-extensions/model-providers/<provider_code>/\`.
4. Build a target binary with \`cargo build --release --target x86_64-unknown-linux-musl\`.
5. Run \`node scripts/node/plugin/cli.js package <plugin-path> --out <dir> --runtime-binary <file> --target x86_64-unknown-linux-musl\`.
6. Run \`node scripts/node/plugin/cli.js demo init <plugin-path>\` to generate the local demo.
`;
}

function readPluginCode(pluginPath) {
  const manifestPath = path.join(pluginPath, 'manifest.yaml');
  if (!fs.existsSync(manifestPath)) {
    return sanitizeCode(getPluginName(pluginPath));
  }

  const content = fs.readFileSync(manifestPath, 'utf8');
  const pluginIdMatch = content.match(/^plugin_id:\s*([^\s#]+)\s*$/m);
  if (pluginIdMatch) {
    const rawPluginId = pluginIdMatch[1];
    const pluginCode = rawPluginId.includes('@')
      ? rawPluginId.slice(0, rawPluginId.indexOf('@'))
      : rawPluginId;
    return sanitizeCode(pluginCode);
  }

  return sanitizeCode(getPluginName(pluginPath));
}

function readManifestField(pluginPath, fieldName, fallbackValue) {
  const manifestPath = path.join(pluginPath, 'manifest.yaml');
  if (!fs.existsSync(manifestPath)) {
    return fallbackValue;
  }

  const content = fs.readFileSync(manifestPath, 'utf8');
  const escapedField = fieldName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const match = content.match(new RegExp(`^${escapedField}:\\s*(.+)$`, 'm'));
  if (!match) {
    return fallbackValue;
  }

  const value = String(match[1] || '').trim();
  return value || fallbackValue;
}

module.exports = {
  createCargoTomlTemplate,
  createExampleModelYaml,
  createI18nTemplate,
  createManifestTemplate,
  createProviderYamlTemplate,
  createReadmeTemplate,
  createRustMainTemplate,
  readManifestField,
  readPluginCode,
};
